// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ayxmiufkbgipytpixtiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5eG1pdWZrYmdpcHl0cGl4dGl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUzODM5MzgsImV4cCI6MjA4MDk1OTkzOH0.GbUvjsy0xJ2lp7IsqS1w3jQwYe9f80m8h2Xo-gVtp78";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);